import React from "react"

import Layout from "../components/layout"
import SEO from "../components/seo"

const NotFoundPage = () => (
    <Layout composition='EmptyBars.org - Cookies'>
    <SEO title="Cookies"/>
    <p>
        Cookies are small text files generated by a website and saved by your web browser to remember
        information about you,similar to a preference file created by a software application.

    </p>
        <p>
            EmptyBars.org neither uses cookies to track nor identify you. The only information we save in your
            browser is the state of the last edited video, which is precisely the information provided by you.
        </p>

        <p>
            If you wish to delete this information now, please click
            on <a href='javascript:(window.localStorage.setItem("emptybarsEditorData", false) || alert("The local storage has been cleaned! Thank you."))'>this link</a>.
        </p>
    </Layout>
)

export default NotFoundPage
